version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y


      - run:
          name: Install awscli
          command: |
            sudo pip install awscli

      - run:
          name: Set AWS Default Region
          command: aws configure set default.region us-east-1

      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            mvn clean package -DskipTests
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            zip -r csye6225-lambda-${CIRCLE_BUILD_NUM}.zip target/csye6225lambda-1.0-SNAPSHOT.jar *.yml
            mv csye6225-lambda-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            cd codedeploy_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 sync codedeploy_artifact s3://${S3_BUCKET_URL}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello CodeDeploy"
      - run:
          name: Check IAM Role and exist Lambda Functions
          command: |
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
            echo ${MY_ENV_VAR}
            echo 'export TopicARN="test"' >> $BASH_ENV
            aws sns list-topics --query Topics[0] --output text
      - run:
          name: Create Lambda Function
          command: |
            aws lambda create-function --function-name ResetPassword --runtime java8 --role arn:aws:iam::509777624845:role/LambdaExeRole --handler handleRequest --description csye6225-lambda-function --code S3Bucket=${S3_BUCKET_URL},S3Key=csye6225-lambda-${CIRCLE_BUILD_NUM}.zip
            aws sns subscribe --topic-arn arn:aws:sns:us-east-1:509777624845:Reset --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:509777624845:function:ResetPassword